name: My Petclinic

on: 
  push:
    branches: ["main" ,"test"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Give permission to mvnw
        run: chmod +x mvnw

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Build JAR
        run: ./mvnw clean package -DskipTests
      
      - name: Build Docker image 
        run: docker build -t petclinic .

  steps:

      - name: Checkout code 
       uses: actions/checkout@v4

      - name: Aws Configure 
        uses: aws-actions/configure-aws-credentials@v4
        with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-key-id: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION}}
        

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Build Docker Img
      #   Run: |
      #    docker build -t pets-clinic .

      - name: Tag img
        Run: |
         docker tag pets-clinic:latest ${{secrets_AWS_ACCOUNT_ID}}.dkr.ecr ${{secrets_AWS_REGION}}.amazonaws.com/pets-clinic:latest

      -  name: Push img to ecr
         Run: |
           docker push pets-clinic:latest ${{secrets_AWS_ACCOUNT_ID}}.dkr.ecr ${{secrets_AWS_REGION}}.amazonaws.com/pets-clinic:latest

           
        

      

      

        

        
        

        
      
  
